Build Latest:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   only:
     - master
   script:
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/skewed-aspect/pokegonav .
     - docker push registry.gitlab.com/skewed-aspect/pokegonav:latest

Build Tagged:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   only:
     - /^v[0-9]{8}/
   script:
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/skewed-aspect/pokegonav .
     - docker push registry.gitlab.com/skewed-aspect/pokegonav:$CI_BUILD_REF_NAME
