build:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/skewed-aspect/pokegonav .
     - docker push registry.gitlab.com/skewed-aspect/pokegonav:latest
