Build Latest:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   script:
     - echo $PORTAL_API_KEY
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/skewed-aspect/pokegonav:latest -t registry.gitlab.com/skewed-aspect/pokegonav:$CI_BUILD_REF_NAME .
     - docker push registry.gitlab.com/skewed-aspect/pokegonav:latest
     - docker push registry.gitlab.com/skewed-aspect/pokegonav:$CI_BUILD_REF_NAME
